# Site settings
title: Anne Kainic
email: annekainic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Anne Kainic is a front end developer, world traveler, vegan foodie, and nostalgic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akainic.github.io" # the base hostname & protocol for your site
github_username:  akainic

# Build settings
markdown: kramdown
